import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <link rel="stylesheet" href="https://especiales.lanacion.com.ar/arc-css/css/site.css"/>
            {children}
        </body>
    </html>
  );
}
